- name: "Install tool deps"
  pip:
    name: "{{item}}"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    extra_args: --index-url https://wheels.galaxyproject.org/simple
  become: True
  become_user: "{{ galaxy_user_name }}"
  with_items:
    - future
    - bcbio-gff
    - biopython
