---
- name: Configure JBrowse
  become: yes
  script: "roles/gonramp/scripts/./jbrowse_config.sh -t {{ tool_dependency_dir }} -u {{ galaxy_user_name }} -n {{ nginx_conf_path }} -a {{apollo_install_location | default('/opt/Apollo')}}/web-app"
  tags:
    - jb_script

- name: update and restart supervisor nginx
  become: yes
  supervisorctl:
    name: nginx
    state: restarted
  tags:
    - jb_supervisor_restart
