#!/usr/bin/env bash

TOOLDEPDIR=""
GALAXYUSER=""
NGINXCONF=""
SRC=""

function usage
{
	echo "usage: ./jbrowse_config.sh [-t directory]"
	echo "	-t: tool dependency directory"
	echo "	-n: nginx.conf file path"
	echo "	-u: galaxy username"
	echo "	-a: apollo web-app location"
}

if [ $# -lt 1 ]; then
	echo "insufficient number of arguments..."
	usage
	exit 1
fi

while [ "$1" != "" ]; do
	case $1 in
		-t | --tool_dependencies )	shift
						TOOLDEPDIR=$1
						;;
		-u | --galaxy_user )		shift
						GALAXYUSER=$1
						;;
		-n | --nginx_conf )		shift
						NGINXCONF=$1
						;;
		-a | --apollo_dir )		shift
						SRC="$1/"
						;;
		* )				usage
						exit 1
	esac
	shift
done

if [ ! -d "$TOOLDEPDIR" ]; then
	echo "Tool dependency directory:"
	echo "$TOOLDEPDIR"
	echo "... does not exist, exiting"
	exit 1
fi

if [ ! -f "$NGINXCONF" ]; then
	echo "nginx configuration file path:"
	echo "$TOOLDEPDIR"
	echo "... does not exist, exiting"
	exit 1
fi

if [ ! -d "$SRC" ]; then
	echo "apollo web-app directory:"
	echo "$SRC"
	echo "... does not exist, exiting"
	exit 1
fi

DST=/var/www/html/jbrowse

JCONF="
// GENERATED BY G-ONRAMP
{
\"plugins\": [ 'G-OnRamp_plugin' ]
}
"

#if [ ! -d "/var/www/html" ]; then
#	mkdir -p /var/www/html
#	chown $GALAXYUSER:users /var/www/html
#fi

#if [ ! -d "$DST" ]; then
ln -s $SRC $DST
#fi

# if [ ! -d "$DST/data" ]; then
# 	mkdir $DST/data
# 	chown $GALAXYUSER:users $DST/data
# fi
#
# if ! cat $DST/jbrowse_conf.json | grep -q G-OnRamp_plugin; then
# 	echo "$JCONF" >| $DST/jbrowse_conf.json
# fi

#if [ ! -d "$DST/plugins/G-OnRamp_plugin" ]; then
#	cd $DST/plugins || exit
#	git clone https://github.com/goeckslab/JBrowse_plugins.git G-OnRamp_plugin
#fi

if ! cat $NGINXCONF | grep -q JBrowse; then
	# add to nginx.conf
	JB_NGINX='\
	\
	# JBrowse addendum\
	location /jbrowse {\
	root    '"$SRC"';\
	}\
\
'
	sed -i.bak 's@listen 80;@listen 80;'"$JB_NGINX"'@g' "$NGINXCONF"
	rm -f "$NGINXCONF".bak
fi
